version: "3.4"
services:
  db:
    image: postgres:latest
    container_name: postgres
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=restapitest
  springboo:
    image: springboot:latest
    container_name: springboot
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

